FROM oven/bun:1.3.8-alpine

WORKDIR /app

RUN apk add --no-cache \
  bash \
  git \
  libgcc \
  libstdc++ \
  netcat-openbsd \
  openssh-client \
  ripgrep

COPY . .

ENV BUN_RUNTIME_TRANSPILER_CACHE_PATH=0

RUN bun install --frozen-lockfile

EXPOSE 8001
